services:
  nordvpn-fritzbox-generator:
    image: ghcr.io/techsuchti/nordvpn-fritzbox-config-generator:1.1.1
    container_name: nordvpn-fritzbox-generator
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
